manifest_version = "0.1.0"

[project]
name = "backend"
type = "motoko"
main = "main.mo"

[build]
commands = ["test -f dist/backend.wasm", "test -f dist/backend.did", "test -f dist/backend.most"]
out = "dist"

[check]
commands = ["test -f dist/backend.wasm", "test -f dist/backend.did", "test -f dist/backend.most"]

[check.fix]
commands = ["test -f dist/backend.wasm", "test -f dist/backend.did", "test -f dist/backend.most"]
